BASE_URL = "https://stellarburgers.education-services.ru"
MAIN_PAGE_URL = f"{BASE_URL}/"
LOGIN_PAGE_URL = f"{BASE_URL}/login"
FORGOT_PASSWORD_URL = f"{BASE_URL}/forgot-password"
RESET_PASSWORD_URL = f"{BASE_URL}/reset-password"
PROFILE_PAGE_URL = f"{BASE_URL}/account/profile"
ORDER_HISTORY_PAGE_URL = f"{BASE_URL}/account/order-history"
ORDER_FEED_URL = f"{BASE_URL}/feed"

API_BASE_URL = f"{BASE_URL}/api"
API_LOGIN_URL = f"{API_BASE_URL}/auth/login"
API_ORDERS_URL = f"{API_BASE_URL}/orders"
API_INGREDIENTS_URL = f"{API_BASE_URL}/ingredients"